# CircleCI automatically reads this file from our repo and uses it for
# configuration. Docs:
# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/sample-config/
version: 2.1

jobs:
  build:
    docker:
      # https://hub.docker.com/r/google/cloud-sdk
      - image: google/cloud-sdk

    steps:
      - checkout

      - restore_cache:
          key: venv-7-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}

      - run:
          name: Install dependencies
          command: |
            git submodule sync
            git submodule update --init
            pip install -U pip
            pip -V
            pip install -U -r requirements.txt
            pip install coverage coveralls

      - run:
          name: Run tests
          command: |
            CLOUDSDK_CORE_PROJECT=oauth-dropins gcloud beta emulators datastore start --no-store-on-disk --consistency=1.0 --host-port=localhost:8089 --quiet &
            sleep 5s
            python3 -m coverage run --include=oauth_dropins/webutil/handlers.py,oauth_dropins/webutil/models.py,oauth_dropins/webutil/util.py -m unittest discover -v -p 'test_*.py'
            kill %1
            python3 -m coverage html -d /tmp/coverage_html
            if [ "$COVERALLS_REPO_TOKEN" != "" ]; then coveralls || true; fi

      - save_cache:
          key: venv-7-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
          paths:
            - "/usr/local/lib/python3.7/dist-packages/"

      - store_artifacts:
          path: /tmp/coverage_html
